services:
  # Backend API
  - type: web
    name: todo-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://todo_postgres_i0ir_user:UuoIjpHz2J8LOneipj4WD4ziMPQaFjed@dpg-d38p84emcj7s738hae1g-a.oregon-postgres.render.com/todo_postgres_i0ir
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/auth/verify

  # Frontend
  - type: web
    name: todo-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: todo-backend
          envVarKey: RENDER_EXTERNAL_URL