services:
  # PostgreSQL Database
  - type: pserv
    name: todo-postgres
    runtime: postgresql
    plan: free

  # Backend API
  - type: web
    name: todo-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: todo-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/auth/verify

  # Frontend
  - type: web
    name: todo-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: todo-backend
          envVarKey: RENDER_EXTERNAL_URL
